### PR TITLE
Add buildroot to update.sh

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by tianon** [comment]
I pondered including this when I wrote this `update.sh`, but ultimately decided against it since updates to buildroot are much more likely to break the build, so require more careful testing than BusyBox version bumps do.

Also, we wouldn't do a full tarball/image rebuild/update _just_ for a Buildroot update -- those would only happen if there also happens to be a BusyBox update and we've got a little extra time to test the Buildroot bump and make sure it's all good.

**Comment by J0WI** [comment]
Should I just revert the changes in `update.sh` or also the `ENV` changes?

**Comment by tianon** [comment]
Also the ENV changes, please.

**Comment by J0WI** [comment]
Okay, I reverted these changes, bu the `uclibc` version is still using an `ENV` (as before).

**Pull request merged**
