### PR TITLE
Ensure we have "/usr/bin/env"

### LINKED ISSUE #156: Symlink /usr/bin to /bin
# Request

Symlink /usr/bin to /bin (like `ln -s /bin /usr/bin`). At minimum, link `/usr/bin/env` to `/bin/env`.

# Background:

On all system, there is an executable called `/usr/bin/env`. For portability reasons, a lot of shell scripts using `#!/usr/bin/env sh`.

Examples from other systems:

OS | env path
-- | --
OpenBSD | /usr/bin/env
FreeBSD | /usr/bin/env
Debian | /usr/bin/env
Ubuntu | /usr/bin/env
CentOS | /usr/bin/env
macOS | /usr/bin/env
SUSE | /usr/bin/env
RHEL | /usr/bin/env
NetBSD | /usr/bin/env
Solaris | /usr/bin/env
BusyBox Docker Image | /bin/env

Most of the linux OS also moving from /bin to /usr/bin. To increase the compatibility between busybox and other os images, I highly recommend to make the binary `/usr/bin/env` available.

### PR DESCRIPTION
**Pull request by tianon**
Closes #156

### CODE REVIEW

**Comment by jkroepke** [comment]
@yosifkit @tianon How long does it take to be available on the official image library/busybox?

**Comment by yosifkit** [comment]
The general process is described [here](https://github.com/docker-library/busybox/tree/c14f260071cc8ab0512d058f60e33c40442059d2#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet). But `busybox` is a little different in that we need to build the rootfs files first. It should be happening soon.

**Comment by jkroepke** [comment]
This is process automated or someone needs to do a manual PR like this? https://github.com/docker-library/official-images/pull/13664

**Comment by tianon** [comment]
It requires us to do a manual rebuild of the rootfs tarballs first, but we wanted to make sure we got https://github.com/docker-library/official-images/pull/13770 in and built first to make sure we got the absolute latest possible uploads in the builds.  I've triggered them now, and will try to monitor their success/failure so we can get an update PR up ASAP. :+1:

**Pull request merged**
