### PR TITLE
Fix Travis CI build failed due to the massive log

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This will redirect buildroot build stdout log inside uclibc variant, currently, the whole log of that build is too huge, so that Travis CI will kill it:

```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).                                          
                                                                                                                                                                             
The job has been terminated
```

This redirection in CI of stdout can prevent this situation.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@tianon anything else I need to do to make it acceptable? Thanks.

**Comment by yosifkit** [comment]
Seems sane to me.

**Comment by yosifkit** [comment]
I learned from @tianon that this build takes too long for TravisCI anyway, regardless of the log length. :cry:

**Comment by PeterDaveHello** [comment]
@yosifkit would you like to enable the CI again to test this PR? Thanks.

**Comment by yosifkit** [comment]
Sure, why not. It is currently on.

**Comment by PeterDaveHello** [comment]
Cool, I just trigger it now!

**Comment by PeterDaveHello** [comment]
@yosifkit now we can see it's fixed!

**Comment by yosifkit** [comment]
It does work, but is still very long. :cry:  Maybe we need to move to a more complex setup to only write to stdout/stderr when the layer fails.  Here is a rough idea that I am testing:

```Dockerfile
# this would just be a COPY, but we've still had docker cache busts with bad COPY "change" detection in docker
FROM debian:jessie

RUN { \
	echo '#!/bin/bash'; \
	echo 'set -e'; \
	echo 'LOG_OUT="$(mktemp)"'; \
	echo 'LOG_ERR="$(mktemp)"'; \
	echo 'trap "{ rm $LOG_ERR $LOG_OUT; }" EXIT'; \
	echo 'trap "{ cat $LOG_OUT; cat >&2 $LOG_ERR; }" ERR'; \
	echo 'sh -ec "$*" >"$LOG_OUT" 2>"$LOG_ERR"'; \
	} > /usr/local/bin/nolog-unless-err \
	&& chmod +x /usr/local/bin/nolog-unless-err

SHELL [ "nolog-unless-err" ]

# rest of Dockerfile
```

The major drawback being the loss of interleaved stdout and stderr; which I think could be solved with a little `sed` magic, so that both outputs go into a single file and then come out .

**Comment by PeterDaveHello** [comment]
If the above code is working, @yosifkit maybe you can push your commit into this PR? Or push to master once this PR been merged, I'll prefer to make the CI working first :)

**Comment by tianon** [comment]
Superseded by #67 :+1:

**Comment by PeterDaveHello** [comment]
hmmm, don't know why it's pending for so long and closed in the end.

**Comment by tianon** [comment]
It was pending for so long because we hadn't yet found a solution that we considered acceptable -- it was finally closed because the "solution" we found was switching CI providers entirely, which avoids the Travis limitations in the first place (which is what this was intended to work around).

**Comment by PeterDaveHello** [comment]
Thanks for the explanation. With all due respect, I think an individual issue ticket would be more appropriate in this situation ;) As PR is for merging, contributors expect PR to be merged, unless there is something needs more fixing but not done yet. If a PR is not acceptable, it should be closed, pending it as an issue ticket may not be that good.

**Pull request closed without merging**
