### PR TITLE
Set an explicit version of uClibc-ng, and bump it to the latest 1.0.13 release

### LINKED ISSUE #9: busybox:uclibc (aka latest) only allows 3 DNS search paths
busybox:glibc works correctly, busybox:uclibc does not. :latest is currently tagged as :uclibc - it looks like this was updated today.

https://git.uclibc.org/uClibc/tree/include/resolv.h#n93

uclibc code shows support for 6

```
# docker run --dns=10.0.0.10 --dns-search=f1 --dns-search=f2 --dns-search=google.internal busybox:glibc nslookup metadata
Unable to find image 'busybox:glibc' locally
glibc: Pulling from library/busybox

Digest: sha256:820e88a5350fab82a8bccad595ffbcd668197abb5b4a718bfe576dd87ab60977
Status: Downloaded newer image for busybox:glibc
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      metadata
Address 1: 169.254.169.254 metadata.google.internal



# docker run --dns=10.0.0.10 --dns-search=f1 --dns-search=f2 --dns-search=f3 --dns-search=google.internal busybox:glibc nslookup metadata
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      metadata
Address 1: 169.254.169.254 metadata.google.internal



# docker run --dns=10.0.0.10 --dns-search=f1 --dns-search=f2 --dns-search=google.internal busybox:uclibc nslookup metadataUnable to find image 'busybox:uclibc' locally
uclibc: Pulling from library/busybox

Digest: sha256:51fef9ff5e7a2b6fc3bd21f4f5542cc56329a1abf5eb336613a6c1731ef681ae
Status: Downloaded newer image for busybox:uclibc
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      metadata
Address 1: 169.254.169.254 metadata.google.internal



# docker run --dns=10.0.0.10 --dns-search=f1 --dns-search=f2 --dns-search=f3 --dns-search=google.internal busybox:uclibc nslookup metadata
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'metadata'
```

### PR DESCRIPTION
**Pull request by tianon**
Fixes #9
Closes #10

The patches in question were merged upstream (http://www.uclibc-ng.org/changeset/2ac8348609b63d6f3a87cb27ce17deff889c6a73/uclibc-ng and http://www.uclibc-ng.org/changeset/8c85b44f6ab42561207365f19b9d1fd69d960771/uclibc-ng), and are included in this latest 1.0.13 release (from 2016-03-13; yesterday). :smile:

cc @thockin @aledbf (wanna give this a go? :+1:)

### CODE REVIEW

**Comment by tianon** [comment]
Ah crap, this needs a bit more, but we're definitely close:
```
ERROR: No hash found for uClibc-ng-1.0.13.tar.xz
```

**Comment by thockin** [comment]
Awesome.  How do I test it - does it get a test label?

**Comment by tianon** [comment]
Easiest way to test it yourself would be to clone the repo and run `./build.sh uclibc` (which will do the appropriate dance to give you a `busybox:uclibc` image locally), but if you'd rather wait I can build it locally and push an image somewhere for simpler testing. :+1:

**Comment by thockin** [comment]
I mean, I already tested the resulting build when I wrote the patch in the
first place, so I am pretty confident it works :)

**Comment by tianon** [comment]
https://hub.docker.com/r/tianon/busybox/ :smile:

**Comment by thockin** [comment]
Are you sure this includes the patch?

```
$ docker run -ti --dns-search=f1 --dns-search=f2 --dns-search=google.com
--dns=8.8.8.8 tianon/busybox nslookup www
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      www
Address 1: 2607:f8b0:4005:801::2004 nuq04s29-in-x04.1e100.net
Address 2: 216.58.192.4 nuq04s29-in-f4.1e100.net

$ docker run -ti --dns-search=f1 --dns-search=f2 --dns-search=f3
--dns-search=google.com --dns=8.8.8.8 tianon/busybox nslookup www
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

nslookup: can't resolve 'www'
```

My `thockin/busybox:uclibc_thockin` works (with a bunch of debug prints)

**Comment by tianon** [comment]
Alright, there was a screwup in my local Docker that caused an older build to be pushed -- I've got this successfully tested and pushed to `tianon/busybox` now:
```console
$ docker pull tianon/busybox
Using default tag: latest
latest: Pulling from tianon/busybox
Digest: sha256:56c2cbe7d6fb1d7b91966f83b3bb8d15b90d5c4664544ac79341acc49ccf42fa
Status: Image is up to date for tianon/busybox:latest
$ docker run -it --rm --dns-search f1 --dns-search f2 --dns-search f3 --dns-search f4 --dns-search google.com --dns 8.8.8.8 tianon/busybox nslookup www
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      www
Address 1: 2607:f8b0:4007:807::2004 lax17s04-in-x04.1e100.net
Address 2: 216.58.219.36 lax17s04-in-f4.1e100.net
```

**Comment by tianon** [comment]
Up to insane levels:
```console
$ docker run -it --rm --dns-search f1 --dns-search f2 --dns-search f3 --dns-search f4 --dns-search f5 --dns-search f6 --dns-search f7 --dns-search f8 --dns-search google.com --dns 8.8.8.8 tianon/busybox nslookup www
Server:    8.8.8.8
Address 1: 8.8.8.8 google-public-dns-a.google.com

Name:      www
Address 1: 2607:f8b0:4007:807::2004 lax17s04-in-x04.1e100.net
Address 2: 216.58.219.36 lax17s04-in-f36.1e100.net
```

**Comment by thockin** [comment]
Confirmed, works now.

**Pull request merged**
